workspace = { members = ["validate-derive"] }

[package]
name = "validator-rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validate-derive = {path = "validate-derive"}
